### ISSUE TITLE
Date Ranges?

### ISSUE THREAD

**Issue by spaceageliving** [arthurperton/statamic-popular#1]
Hi Arthur, just saw this new Addon and it looks really cool!

One question--is it possible to scope the view counts to a time window? For example, to show the list of the most popular stories over the past week, or month (vs. just all time, which is what it appears is the case now)?

A related question--can the count be scoped to a specific collection? For example, what are the top stories in "Recipes" as opposed to "Tips"?

TIA, really love this Addon, great work!

**Comment by arthurperton** [comment]
Thank you!

> One question--is it possible to scope the view counts to a time window? For example, to show the list of the most popular stories over the past week, or month (vs. just all time, which is what it appears is the case now)?

No. That is actually a nice feature though. It won't be trivial to add because it doesn't match with the highly performant way data is currently collected and retrieved in this add-on. I'll give it some thought, but don't expect this feature soon (if ever).

> A related question--can the count be scoped to a specific collection? For example, what are the top stories in "Recipes" as opposed to "Tips"?

Yes that is the most common use case actually, see the [example in the docs](https://statamic.com/addons/arthurperton/popular/docs#templating). By leveraging the power of the Collection tag, you can scope to any collection(s) you want.

**Comment by spaceageliving** [comment]
Thanks Arthur!
